esphome:
  name: "esphome-office-deskleds"

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "70fd1522125a8b23adc72f3a7bbc2477"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Office-Desk-Led-Strips"
    password: "3JG6m3Dt6BHX"

captive_portal:

# https://esphome.io/components/binary_sensor/
binary_sensor:
  - platform: gpio
    name: "Led Strip 1 Button"
    pin:
      number: D2
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 10ms
    on_press:
      then:
        - switch.toggle: ledstrip1
  - platform: gpio
    name: "Led Strip 2 Button"
    pin:
      number: D3
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 10ms
    on_press:
      then:
        - switch.toggle: ledstrip2

# https://esphome.io/components/switch/gpio
switch:
  - platform: gpio
    id: ledstrip1
    name: "Led Strip 1"
    pin:
      number: D5
      inverted: true
  - platform: gpio
    id: ledstrip2
    name: "Led Strip 2"
    pin:
      number: D6
      inverted: true
  - platform: gpio
    id: output3
    name: "Output 3"
    pin:
      number: D7
      inverted: true
  - platform: gpio
    id: output4
    name: "Output 4"
    pin:
      number: D8
      inverted: true
